In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3,4,5])
print(x)


[1 2 3 4 5]


In [4]:
print("1st elemnt of the array  : ", x[0])
print("2st elemnt of the array  : ", x[1])
print("3st elemnt of the array  : ", x[2])
print("4st elemnt of the array  : ", x[3])

1st elemnt of the array  :  1
2st elemnt of the array  :  2
3st elemnt of the array  :  3
4st elemnt of the array  :  4


In [5]:
print("1st elemnt of the array  : ", x[-5])
print("2st elemnt of the array  : ", x[-4])
print("3st elemnt of the array  : ", x[-3])
print("4st elemnt of the array  : ", x[-2])

1st elemnt of the array  :  1
2st elemnt of the array  :  2
3st elemnt of the array  :  3
4st elemnt of the array  :  4


In [6]:
x[3]=20
print(x)

[ 1  2  3 20  5]


In [7]:
x= np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print("Elemnet at (0 ,0 ) : ",x[0,0])
print("Elemnet at (0 ,0 ) : ",x[0,1])
print("Elemnet at (0 ,0 ) : ",x[0,2])
print("Elemnet at (0 ,0 ) : ",x[1,0])
print("Elemnet at (0 ,0 ) : ",x[1,1])

Elemnet at (0 ,0 ) :  1
Elemnet at (0 ,0 ) :  2
Elemnet at (0 ,0 ) :  3
Elemnet at (0 ,0 ) :  4
Elemnet at (0 ,0 ) :  5


In [9]:
x[0,0]=20
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [10]:
x = np.array([1,2,4,5])
print(x)
x = np.delete(x,[0,4])
print(x)

[1 2 4 5]


IndexError: index 4 is out of bounds for axis 0 with size 4

In [1]:
X = np.ones((4, 4)) * np.arange(1, 5)


NameError: name 'np' is not defined