In [1]:
import numpy as np


In [2]:
x = np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
print( x [ x > 16] )

[17 18 19 20 21 22 23 24]


In [11]:
print( x [ x <= 7 ] )

[0 1 2 3 4 5 6 7]


In [12]:
print(x [ (x > 10) & (x < 17) ] )

[11 12 13 14 15 16]


In [13]:
x[ (x > 10) & (x < 17)]=-1
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, -1, -1, -1, -1],
       [-1, -1, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

print(np.intersect1d(x,y))
print(np.setdiff1d(x,y))
print(np.union1d(x,y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [60]:
x = np.random.randint(1 , 11, size=(10,))
x

array([2, 7, 4, 9, 8, 8, 2, 1, 9, 5])

In [61]:
print(np.sort(x))
print(x)

[1 2 2 4 5 7 8 8 9 9]
[2 7 4 9 8 8 2 1 9 5]


In [62]:
print(np.sort(np.unique(x)))

[1 2 4 5 7 8 9]


In [63]:
print(x)

[2 7 4 9 8 8 2 1 9 5]


In [65]:
x.sort()
x

array([1, 2, 2, 4, 5, 7, 8, 8, 9, 9])

In [67]:
x =np.random.randint(1,11 ,size=(5,5))
x

array([[ 1,  8,  6,  3,  3],
       [ 8,  1,  9, 10, 10],
       [ 1,  2,  9,  4,  5],
       [ 9,  7,  8,  8,  2],
       [ 4, 10,  1,  4,  1]])

In [68]:
print(np.sort(x,axis=0))


[[ 1  1  1  3  1]
 [ 1  2  6  4  2]
 [ 4  7  8  4  3]
 [ 8  8  9  8  5]
 [ 9 10  9 10 10]]


In [69]:
print(np.sort(x,axis=1))

[[ 1  3  3  6  8]
 [ 1  8  9 10 10]
 [ 1  2  4  5  9]
 [ 2  7  8  8  9]
 [ 1  1  4  4 10]]
