In [ ]:
import numpy as np
a =np.zeros(10)
a

In [ ]:
z = np.zeros(10)
z
z.shape = ( 10 , 1 )
z


In [14]:
z= np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
z = np.empty(3)
z

array([2.12199579e-314, 0.00000000e+000, 6.89715642e-321])

In [22]:
z = np.linspace(2,10,5)
z
type(z)

numpy.ndarray

In [26]:
z = np.array([10,20])
?z

Type:            ndarray
String form:     [10 20]
Length:          2
File:            c:\users\king\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages\numpy\__init__.py
Docstring:       <no docstring>
Class docstring:
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
--------

In [28]:
b_list=[[9,8,7.6,5,4,3],[1,2,3,4,5,6,7]]
z =np.array(b_list)
z

array([list([9, 8, 7.6, 5, 4, 3]), list([1, 2, 3, 4, 5, 6, 7])],
      dtype=object)

In [29]:
np.random.seed(0)
z1 = np.random.randint(10,size=6)
z1

array([5, 0, 3, 3, 7, 9])

In [1]:

photo = io.imgread("download.jpg")
type(photo)

photo =io.down

SyntaxError: invalid syntax (<ipython-input-1-d7c367368e79>, line 1)