In [ ]:
import numpy as np



In [ ]:
1.ndarray[start:end]
2.ndarray[start:]
3.ndarray[:end]

In [5]:
x = np.arange(1,21).reshape(4,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [7]:
z = x[1:4,2:5]
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [9]:
z = x[:3,2:]
z

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [12]:
z = x[:,2]
z

array([ 3,  8, 13, 18])

In [13]:
z = x[:,2:3]
z

array([[ 3],
       [ 8],
       [13],
       [18]])